---
title: "figures"
author: "Courtney B. Hilton"
date: "24/03/2022"
output: pdf_document
---

```{r rmd_config, include = FALSE}

# chunk options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# prevent scientific notation for numerals
options(scipen = 999)

```

```{r load-libraries}

library(pacman)
p_load(
  lmerTest,
  broom,
  broom.mixed,
  sf,
  colorspace,
  Rmisc,
  ggtext,
  ggpubr,
  kableExtra,
  Hmisc,
  gridExtra,
  scales,
  psycho,
  patchwork,
  png,
  here,
  sjmisc,
  sjPlot,
  tidyverse,
  scales,
  glue, 
  rsq,
  ggpubr,
  hms,
  lubridate,
  ggpattern
)

# save figure outputs here
knitr::opts_chunk$set(fig.path = here("viz", "figures", ""))

# create list to store plots
plots <- list()

# setup plotting theme
custom_theme <- theme_bw() +
  theme(legend.position = "none",
        legend.key = element_rect(fill = "white", colour = "black"),
        axis.text = element_text(size = 10, color = "black"))

theme_set(custom_theme)

colours <- c("#619CFF","#F8766D","#00BA38")

```

```{r load-data}

# 1. load all preprocessed data from builder
load(here("results", "preprocessed_data.RData"))
# 2. load analyses results
load(here("results", "analyses.RData"))
# 3. results from music feature analysis
# load(here("results", "selected_features.RData"))
load(here("results", "lasso_analyses.RData"))
# 4. discogrpahy map
discogMap <- read_csv(here('data', "discogMap.csv")) %>%
  filter(type != "Love") %>%
  mutate(type = as.factor(type))

```

```{r fig1, fig.height = 7.7, fig.width = 12}

experiment_schematic <- readPNG(here("viz", "kfc_procedureSchematic2.png"))
plot.new()
rasterImage(experiment_schematic,0,0,1,1)

```

```{r fig2, fig.width = 6.2, fig.height = 3}

d_prime_pointrange <- ggplot(kids$d$avg %>% bind_rows, aes(y = avg_d, x = factor(type, levels = c("dance", "lullaby", "healing")),
                                 colour = factor(type, levels = c("dance", "lullaby", "healing" ))
                     )) + # fill = as.factor(type, levels = c("healing",  "lullaby", "dance"))
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high), fatten = 5, size = .3,
                  position = position_dodge(width = .3), alpha = .8, pch = 16) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  scale_colour_manual(values = c("#619CFF", "#00BA38", "#F8766D"),
                      name = "") +
  scale_y_continuous(breaks = seq(0,2,1/5)) +
  labs(x = "Cohort Mean", y = "Sensitivity (d')") +
  coord_cartesian(ylim = c(0,1.8), clip = "off") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none",
        plot.margin = margin(0,20,0,0))


d_prime_age_pointrange <- ggplot(kids$d$ages %>% bind_rows(), 
       aes(x = age, y = d_prime,
           colour = factor(type, levels = c("dance",  "lullaby", "healing"))
       )) +
  geom_smooth(method = "lm",
              aes(group = type), alpha = .3, key_glyph = "pointrange") +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high), fatten = 5, size = .3,
                  position = position_dodge(width = .3), alpha = .8, pch = 16,
                  key_glyph = "pointrange") +
  # ADDING ADULT DATA
  geom_point(data = bind_rows(adults$d$group) %>% 
               filter(type != "love") %>%
               mutate(age = 19),
             size = 2.5, alpha = .8, pch = 17,show.legend = FALSE) +
  # ADDING SEPARATION LINE
  annotate("segment", x = 17.5, xend = 17.5, y = 0.1, yend = 1.8, colour = "black", size = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  scale_x_continuous(breaks = c(seq(from = 1, to = 16, by = 1), 16, 16, 19, 19), 
                     labels = c(seq(from = 1, to = 16, by = 1), " ", " ", "Adults", " ")) +
  scale_colour_manual(values = c("#619CFF", "#00BA38","#F8766D"),
                      name = "",
                      labels = c("Dance", "Lullaby", "Healing")) +
  labs(x = "Age (Years)", y = "") +
  scale_y_continuous(breaks = seq(0,2,1/5)) +
  coord_cartesian(ylim = c(0,1.8), xlim = c(4,20)) +
  theme_bw() +
  theme(panel.grid.minor.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

fig2 <- d_prime_pointrange + d_prime_age_pointrange +
  plot_annotation(tag_levels = "a") +
  plot_layout(widths = c(1,5))

fig2

```

```{r fig3, fig.width = 9, fig.height = 6.5, dev='quartz_pdf'}

KFC_FC_corr_plot <- function(type_x, color_x, y_show, x_show) {
  ggplot(data = filter(guesses$by_type, guess == type_x), aes(x = FC*100, y = KFC*100)) +
    geom_point(size = 2, aes(colour = factor(type)), alpha = .6, pch = 16) +
    scale_colour_manual(values = c("#619CFF", "#F8766D", "#00BA38")) +
    scale_x_continuous(limits = c(0,100)) +
    scale_y_continuous(limits = c(0,100)) +
    guides(colour = "none") +
    geom_smooth(method='lm', color = 'black') +
    stat_cor(aes(label = ..rr.label..),
      label.x = 0, label.y = 90, color = "black") + 
    labs(title = str_to_title(paste("%", type_x, "guesses")),colour = "Song type",
         x = ifelse(x_show, "Adults", ""), 
         y = ifelse(y_show, "Children", "")) +
    theme(plot.title = element_text(color = color_x),
          aspect.ratio=1, 
          plot.margin = margin(0,4.5,0,0),
          panel.grid.minor = element_blank()) +
    coord_cartesian(clip = 'off')
}

# correlation scatter plots
plots$corr$dance <- KFC_FC_corr_plot("dance", "#619CFF",1,1)
plots$corr$lullaby <- KFC_FC_corr_plot("lullaby", "#00BA38",1,1)
plots$corr$healing <- KFC_FC_corr_plot("healing", "#F8766D",1,1)

# create feature plots showing R^2 for each feature
for (type_x in c("dance", "lullaby", "healing")) {
  # calculate R^2 for each feature in simple linear model
  for (data_x in c("KFC", "FC")) {
    for (feature_x in selected_features[[type_x]]$feats[1:5]) { # selecting the top 5 features to show in the plot
      x <- reformulate(selected_features[[type_x]]$feats[selected_features[[type_x]]$feats != feature_x], 
                       response = paste(data_x, type_x, sep = "_"))
      mods[[type_x]][[data_x]][[feature_x]] <- lm(x, data = songs) 
      
      mods[[type_x]][[data_x]][[feature_x]] <- rsq.partial(
        mods$feature[[data_x]][[type_x]],
        mods[[type_x]][[data_x]][[feature_x]]
      )$partial.rsq %>% 
        as_tibble() %>% 
        mutate(feature = feature_x,
               partial_r.squared = value) %>% 
        select(-value)
    }
  }
  # turn into a tidy long tibble 
  mods$features[[type_x]] <- mods[[type_x]] %>% 
    as_tibble() %>% 
    pivot_longer(cols = c(KFC, FC), names_to = "participant", values_to = "data") %>% 
    unnest() %>% 
    mutate(feature = fct_reorder(feature, partial_r.squared))
}

# plot features ordered by size
feature_plot <- function(type_x, labels) {
  ggplot(mods$features[[type_x]],
         aes(y = feature, x = partial_r.squared, fill = participant)) +
    # geom_col(position = "dodge") +
    geom_col_pattern(
    aes(pattern_alpha = participant),
    position = "dodge",
    pattern = "stripe",
    color = "black",
    pattern_fill = "black",
    pattern_spacing = 0.05,
    pattern_density = 0.05
  ) + 
  scale_pattern_alpha_manual(values = c(0,1) %>% rev) +
    labs(y = "", x = bquote("Partial R"^2)) + #, title = type_x
    scale_fill_manual(values = case_when(
      type_x == "dance" ~ c(darken("#619CFF", .3), "#619CFF"),
      type_x == "lullaby" ~ c(darken("#00BA38", .3), "#00BA38"),
      type_x == "healing" ~ c(darken("#F8766D", .3), "#F8766D")
    ),
    labels = c("Children", "Adults")) +
    guides(fill = guide_legend(override.aes = list(fill = c("grey50", "grey80") %>% rev,
                                                 pattern = c("stripe", "none") %>% rev,
                                                 pattern_spacing = 0.015,
                                                 pattern_density = 0.2)),
         pattern_alpha = "none") +
    scale_y_discrete(labels = labels) +
    lims(x = c(0,.5)) +
    theme(
      legend.position = "none",
      aspect.ratio = 1,
      panel.grid.minor = element_blank(),
      axis.text = element_text(size = 8, color = "black"),
      axis.text.y = element_markdown()
    )
}

plots$feature$dance <- feature_plot("dance", c(
  "<i style='color: green;'>\u25B2</i> Accentuation",
  "<i style='color: green;'>\u25B2</i> Tempo",
  "<i style='color: green;'>\u25B2</i> Metrical Clarity",
  "<i style='color: green;'>\u25B2</i> Duple rhythm",
  "<i style='color: red;'>\u25BC</i> Note duration"
) %>% rev)
plots$feature$lullaby <- feature_plot("lullaby", c(
  "<i style='color: red;'>\u25BC</i> Accentuation",
  "<i style='color: red;'>\u25BC</i> Melodic simplicity",
  "<i style='color: red;'>\u25BC</i> Tempo",
  "<i style='color: green;'>\u25B2</i> Note duration",
  "<i style='color: green;'>\u25B2</i> Minor tonality"
  ) %>% rev)
plots$feature$healing <- feature_plot("healing", c(
  "<i style='color: red;'>\u25BC</i> Metrical clarity",
  "<i style='color: red;'>\u25BC</i> Tempo",
  "<i style='color: green;'>\u25B2</i> Major tonality",
  "<i style='color: red;'>\u25BC</i> Syncopation",
  "<i style='color: green;'>\u25B2</i> Vibrato"
) %>% rev)


fig3 <- plots$corr$dance + plots$corr$lullaby + plots$corr$healing +
  plots$feature$dance + plots$feature$lullaby + plots$feature$healing +
  plot_layout(heights = 1, guides = "collect") + plot_annotation(tag_levels = "a") &
  theme(legend.position = "bottom", legend.title = element_blank())

fig3

```

```{r supplementary-fig1}

# age distribution
KFC_clean %>%
  group_by(user_id, gender) %>%
  summarise(age = mean(age)) %>%
  group_by(age, gender) %>%
  summarise(Freq = n()) %>%
  arrange(desc(age)) %>%
  ggplot(., aes(fill = gender, x = age, y = Freq)) +
  geom_bar(stat = 'identity') +
  labs(x = "Age (Years)", y = "Number of Participants", fill = "Gender") +
  scale_x_continuous(breaks = seq(4, 16, by = 1)) +
  scale_fill_discrete(name = "Gender") +
  scale_fill_viridis_d() +
  theme_bw() +
  theme(panel.grid.minor.x = element_blank())

```

```{r supplementary-fig2, fig.width = 6, fig.height = 4}

# making dataset names match before merging
countries <- kid_participants %>%
  count(country) %>%
  arrange(desc(n)) 

# source: https://www.naturalearthdata.com/downloads/110m-cultural-vectors/
world_map <- read_sf(here('data', "map_shapefiles/ne_110m_admin_0_countries.shp")) %>%
  filter(ISO_A3 != "ATA") %>% # removing antartica
  left_join(countries, by = c("NAME_LONG" = "country")) %>%
  mutate(n = ifelse(is.na(n), 0,n))


#scale_breaks = round(exp(seq(log(571), 0, length.out = 6)))

dicog_map_sf <- discogMap %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)


ggplot() +
  geom_sf(data = world_map, fill = "#fff3d6", lwd = 0.1) +
  geom_point(data = dicog_map_sf, aes(color = as.factor(type),  geometry = geometry, fill = as.factor(type)), stat = "sf_coordinates", shape = 21) +
  scale_color_manual(values = darken(colours, 0.3), name = "song type", guide = FALSE) +
  scale_fill_manual(values = colours) +
  coord_sf() +
  theme_void() +
  theme(legend.position = "bottom",
        legend.title = element_blank(), 
        plot.background = element_rect(fill = "#EFFFFC66"))

```

```{r supplementary-fig3, fig.align='center', fig.height=5, fig.width=6}

kids_complete <- read_csv(here("results", "KFC_clean.csv")) %>% 
  group_by(user_id) %>% 
  summarise(
    country = unique(country),
    date = first(date),
    age = unique(age)
  )

adults_full <- read_csv(here("results", "preprocessed_FC.csv")) %>% 
  group_by(user_id) %>% 
  summarise(
    date = first(created_at),
    country = unique(country)
  )

# annotation data
dat_text <- data.frame(
  label = c(
    "Featured in Verge.com article",
    "Mass email to<br>subscribers", 
    "Science paper published<br>(Mehr et al., 2019)",
    "Featured in popular<br>Youtube video (~1M views)",
    "Featured on front page of Reddit",
    "Featured on front page of Reddit"
    ),
  participant = factor(c(rep("Adults", 5), "Children"), levels = c("Children", "Adults")),
  date = c(
    ymd_hms("2019-09-01 01:00:00"), # verge
    ymd_hms("2019-06-01 01:00:00"), # blah
    ymd_hms("2019-08-01 01:00:00"), # science
    ymd_hms("2019-10-01 01:00:00"), # youtube
    ymd_hms("2021-01-01 01:00:00"), # adult Reddit
    ymd_hms("2021-02-01 01:00:00") # kid Reddit
  ),
  y = c(
    12000, # verge
    2500, # blah
    5000, # science
    8000, # youtube
    8000, # adult Reddit
    350 #kid Reddit
  )
)

dat_arrow <- data.frame(
  x = c(
    ymd_hms("2019-09-01 01:00:00"), # science paper
    ymd_hms("2019-11-01 01:00:00"), # youtube
    ymd_hms("2019-03-12 01:00:00"), # Verge
    ymd_hms("2020-06-22 01:00:00"), # Reddit
    ymd_hms("2020-07-25 01:00:00") # Reddit2
  ),
  xend = c(
    ymd_hms("2019-11-10 01:00:00"),  # science paper
    ymd_hms("2020-02-27 01:00:00"), # youtube
    ymd_hms("2019-02-09 01:00:00"), # Verge
    ymd_hms("2020-05-15 01:00:00"), # Reddit
    ymd_hms("2020-06-15 01:00:00") # Reddit2
  ),
  y = c(4000, 7000, 12000, 8000, 350),
  yend = c(2400, 5500, 11500, 7500, 335),
  participant = factor(c(rep("Adults", 4), "Children"), levels = c("Children", "Adults"))
)

kids_complete %>% 
  select(user_id, date) %>% 
  mutate(participant = "Children") %>% 
  bind_rows(., adults_full %>% select(user_id, date) %>% 
              mutate(participant = "Adults")) %>% 
  mutate(participant = factor(participant, levels = c("Children", "Adults"))) %>% 
  ggplot(., aes(x = date)) +
  geom_histogram(bins = 100, alpha = 0.9) + 
  scale_x_datetime(
    limits = c(ymd_hms("2019-01-01 04:41:29"), ymd_hms("2022-04-01 04:41:29"))
  ) +
  labs(
    y = "Count (participants)",
    x = NULL
  ) + 
  facet_grid(vars(participant), scales = "free") +
  scale_y_continuous(labels = comma) +
  # adding text annotations
  geom_richtext(data = dat_text, aes(y = y, label = label), size = 2.5, label.size = NA, fill = NA) +
  # adding some clarifying arrows
  geom_curve(data = dat_arrow, aes(x=x,xend=xend,y=y,yend=yend),
             color = "black", size = .2, curvature = 0, arrow = arrow(length = unit(0.02, "npc"))) +
  theme_bw() + 
  theme(
    strip.background = element_rect(fill = "white", color = "white"),
    strip.text = element_text(size = 11)
  )

```

```{r supplementary-fig4, fig.align='center', fig.height=12, fig.width=12}

# function to extract out time/date info
process_times <- function(data, timezone) {
  data %>% 
    mutate(
      date = with_tz(ymd_hms(date), tzone = timezone),
      time = hms::as_hms(date),
      day = weekdays(date),
      month = month(date),
      year_day = yday(date)
    ) %>% 
    mutate(
      holiday = ifelse(year_day %in% c(
        330:332, # thanksgiving
        355:365, # christmas
        1, # christmas
        30:31, # wid-winter break
        95:99  # Spring break
      ) |
        day %in% c("Saturday", "Sunday"), 1, 0)
    )
}


polar_time_plottter <- function(data, title) {
  data %>% 
    ggplot(., aes(x = time, fill = hour(time) %in% c(22,23,0,1,2,3,4,5))) + 
    geom_histogram(
      boundary = hms("00:00:00"),
      alpha = 0.8, color = "black", binwidth = 60*60,
      show.legend = FALSE,
      aes(y = after_stat(count / sum(count)))
      ) + 
    coord_polar() +
    scale_x_time(
      limits = c(hms("00:00:00"), hms("24:00:00")),
      breaks = scales::date_breaks("2 hours"),
      labels = seq(0,24,2) %>% as.character()
    ) +
    labs(
      y = "N participants",
      x = NULL,
      title = title
    ) + 
    scale_y_continuous(labels = percent, limits = c(0, 0.13)) +
    scale_fill_manual(values = c("#BE830E", lighten("#BE830E", 0.6))) +
    theme_light() + 
    theme(
      plot.title = element_markdown(hjust = 0.5),
      axis.line = element_blank(),
      panel.border = element_blank(),
      axis.title = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      legend.position = "none"
    )
}

percent_time_plotter <- function(kid_data, adult_data) {
  kid_data %>% 
    # filter(country %in% country_to_plot) %>% 
    select(user_id, time) %>% 
    mutate(participant = "Children") %>% 
    bind_rows(., adult_data %>% select(user_id, time) %>% mutate(participant = "Adults")) %>% 
    mutate(late = ifelse(hour(time) %in% c(22,23,0,1,2,3,4,5), 1, 0)) %>% 
    group_by(participant) %>% 
    count(late) %>% 
    mutate(pct = n / sum(n),
           y_pos = ifelse(late == 1, pct - (pct / 2), 1 - (pct / 2)),
           participant = factor(participant, levels = c("Children", "Adults"))) %>% 
    # let's make the plot
    ggplot(., aes(x = participant, y = pct, fill = as.factor(late))) + 
    geom_col(color = "black") + 
    geom_text(aes(label = percent(pct), y = y_pos)) +
    scale_y_continuous(labels = percent, limits = c(0,1)) +
    scale_x_discrete(position = "top") +
    labs(
      y = NULL,
      x = NULL
    ) +
    scale_fill_manual(labels = c("5am - 10pm", "10pm - 5am"),
                      values = c("#BE830E", lighten("#BE830E", 0.6))) +
    theme_void() + 
    theme(
      legend.title = element_blank(),
      legend.position = "right",
      axis.text.x.top = element_text(color = "black", size = 12)
    )
}


children <- list()
children$US <- process_times(kids_complete %>% filter(country == "United States", age <= 12), "America/New_York") 
children$UK <- process_times(kids_complete %>% filter(country == "United Kingdom", age <= 12), "Europe/London") 
children$Turkey <- process_times(kids_complete %>% filter(country == "Turkey", age <= 12), "Europe/Istanbul") 
children$Germany <- process_times(kids_complete %>% filter(country == "Germany", age <= 12), "Europe/Berlin") 
children$NZ <- process_times(kids_complete %>% filter(country == "Aotearoa/New Zealand", age <= 12), "Pacific/Auckland") 

adults <- list()
adults$US <- process_times(adults_full %>% filter(country == "United States"), "America/New_York") 
adults$UK <- process_times(adults_full %>% filter(country == "United Kingdom"), "Europe/London") 
adults$Turkey <- process_times(adults_full %>% filter(country == "Turkey"), "Europe/Istanbul") 
adults$Germany <- process_times(adults_full %>% filter(country == "Germany"), "Europe/Berlin") 
adults$NZ <- process_times(adults_full %>% filter(country == "New Zealand"), "Pacific/Auckland") 


# United States
kids_US <- polar_time_plottter(children$US, "Children from the **United States**")
adults_US <- polar_time_plottter(adults$US, "Adults from the **United States**")
US_percent <- percent_time_plotter(children$US, adults$US)

# Turkey
kids_turk <- polar_time_plottter(children$Turkey, "Children from **Turkey**")
adults_turk <- polar_time_plottter(adults$Turkey, "Adults from **Turkey**")
turk_percent <- percent_time_plotter(children$Turkey, adults$Turkey)

# United Kingdom
kids_UK <- polar_time_plottter(children$UK, "Children from the **United Kingdom**")
adults_UK <- polar_time_plottter(adults$UK, "Adults from the **United Kingdom**")
UK_percent <- percent_time_plotter(children$UK, adults$UK)

# Germany
kids_Germany <- polar_time_plottter(children$Germany, "Children from **Germany**")
adults_Germany <- polar_time_plottter(adults$Germany, "Adults from **Germany**")
Germany_percent <- percent_time_plotter(children$Germany, adults$Germany)

# NZ
kids_NZ <- polar_time_plottter(children$NZ, "Children from **New Zealand**")
adults_NZ <- polar_time_plottter(adults$NZ, "Adults from **New Zealand**")
NZ_percent <- percent_time_plotter(children$NZ, adults$NZ)

layout <- "
AAABBBC
DDDEEEF
GGGHHHI
JJJKKKL
MMMNNNO
"

kids_US + adults_US + US_percent +
  kids_turk + adults_turk + turk_percent + 
  kids_UK + adults_UK + UK_percent +
  kids_Germany + adults_Germany + Germany_percent + 
  kids_NZ + adults_NZ + NZ_percent +
  plot_layout(design = layout, guides = "collect") &
  theme(legend.position = "bottom")

```

```{r supplementary-fig5, fig.width = 6, fig.height = 4}

KFC_clean %>%
  select(rt, age, user_id) %>%
  filter(rt < 100000) %>%
  mutate(rt = rt / 1000) %>%   # convert to units of seconds
  ggplot(., aes(x = factor(age), y = rt)) +
  geom_boxplot(outlier.shape = NA, fill = "grey90") +
  geom_violin(alpha = 0.3, fill = "yellow") +
  #geom_smooth(aes(x = as.numeric(age-2)), method = "lm", color = "red", size = 1) +
  scale_y_log10() +
  labs(
    y = "Response Time (s)",
    x = "Age (Years)"
  ) +
  theme_bw()

```


```{r supplementary-fig6, fig.width = 5, fig.height = 7}

proportion_plot <- KFC_clean %>% 
  nest_by(age) %>% 
  summarise(proportions = list(janitor::tabyl(data$response))) %>% 
  unnest(proportions) %>% 
  rename(type = `data$response`) %>% 
  mutate(type = factor(type, levels = c("DANCE", "LULLABY", "HEALING"))) %>% 
  ggplot(., aes(x = as_factor(age), y = percent, fill = type)) + 
  geom_col() + 
  scale_y_continuous(labels = percent) + 
  scale_fill_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
  labs(
    x = "Age (Years)",
    y = "Average Guesses (%)"
  ) + 
  theme(
    legend.position = "top",
    legend.title = element_blank()
  )

criterion_plot <- ggplot(kids$d$ages %>% bind_rows(), 
                                 aes(x = age, y = c,
                                 colour = factor(type, levels = c("dance",  "lullaby", "healing"))
                     )) +
  geom_smooth(method = "lm",
              aes(group = type), alpha = .3, key_glyph = "pointrange") +
  geom_point(size = 2, position = position_dodge(width = .3), alpha = .8, pch = 16) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  scale_x_continuous(breaks = seq(from = 1, to = 17, by = 1)) +
  scale_colour_manual(values = c("#619CFF", "#00BA38","#F8766D")) +
  labs(x = "Age (Years)", y = "Criterion") +
  scale_y_continuous(breaks = seq(0,1,1/5)) +
  coord_cartesian(ylim = c(0,1), clip = "off") +
  theme_bw() +
  theme(panel.grid.minor.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none")


proportion_plot / criterion_plot + 
  plot_annotation(tag_levels = "a")

```

```{r supplementary-fig7, fig.align = "center", fig.height = 7.5, fig.width = 12, out.extra = 'trim={0 2.5cm 0 2.5cm}, clip'}

experiment_schematic <- readPNG(here("analysis", "d-simulation_0.74hit_miss_0.35fa_cr_2099participants.png"))
plot.new()
rasterImage(experiment_schematic,0,0,1,1)

```

```{r supplementary-fig8, fig.width = 6.5, fig.height = 4.5}

covariate_plotter <- function(covariate, title, color) {
  KFC_clean %>% 
  drop_na({{covariate}}) %>% 
  group_by({{covariate}}, user_id) %>% 
  summarise(avg = mean(correct),
            sdev = sd(correct)) %>% 
  ggplot(., aes(x = {{covariate}}, y = avg*100)) +
  geom_boxplot(outlier.shape = NA, fill = "grey90", alpha = 0.7) +
  geom_violin(alpha = 0.3, fill = color) +
  coord_cartesian(ylim = c(0,100)) +
  labs(x = NULL,
       y = "Personwise Average \nAccuracy (%)",
       title = title) +
  coord_flip() +
  theme_bw() + 
  theme(
    plot.title = element_text(hjust = 0.5)
  )
}

plots$parentSing <- covariate_plotter(singOften, "Frequency of\n Parental Singing", "orange")
plots$recMusic <- covariate_plotter(playMusicOften, "Frequency of \nRecorded Music", "green")

plots$parentSing + plots$recMusic + plot_annotation(tag_levels = "a")

```

```{r supplementary-fig9, fig.align = "center", fig.height = 3, fig.width = 5}

plot_model(lm(KFC_FC_correlation ~ 0 + age*response, 
              data = kids$corr$wFC %>% 
                mutate(response = str_to_title(response))),
           type = "pred", terms = c("age", "response"),
           colors = colours,
           show.data = TRUE) + 
  scale_x_continuous(breaks = seq(3,16)) + 
  coord_cartesian(ylim = c(0,1)) +
  labs(
    y = "Child-Adult Correlation (R<sup>2</sup>)",
    x = "Age (Years)",
    title = NULL
  ) +
  custom_theme + 
  theme(
    legend.position = "right",
    legend.title = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.title.y = element_markdown()
  )

```

